### ISSUE TITLE
Error!!! HELP!!

### ISSUE THREAD

**Issue by jeastudi** [thuyngch/Iris-Recognition#17]
Hi, I’m writing you because I’m logging the casia database using the file "enroll-casia.py", when running the following errors arise

https://user-images.githubusercontent.com/38151088/70859911-47e37380-1ef9-11ea-80a6-ab89372ecb27.png

Additionally I have problems with "verify.py", since they all give me result = -1 

I hope you can help me, I find myself in an emergency

**Comment by ianni67** [comment]
got the same error. There are issues with the segmentation that I could not solve. I get the same error with all the images in the casia1 folder.

`python3 enroll-single.py --file ../CASIA1/30/030_1_1.jpg 
>>> Enroll for the file  ../CASIA1/001_1_1.jpg
Traceback (most recent call last):
  File "enroll-single.py", line 33, in <module>
    template, mask, file = extractFeature(args.file)
  File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/extractFeature.py", line 47, in extractFeature
    ciriris, cirpupil, imwithnoise = segment(im, eyelashes_thres, use_multiprocess)
  File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/segment.py", line 30, in segment
    rowp, colp, rp = searchInnerBound(eyeim)
  File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/boundary.py", line 26, in searchInnerBound
    Y = img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by m4hi2** [comment]
I've got the same error. @thuyngch  can you please look at this? Thank you for your amazing work.

**Comment by ramyaksrinivas** [comment]
same i got please anyone who solved it share and help me

**Comment by AfroJosh** [comment]
> Hi, I’m writing you because I’m logging the casia database using the file "enroll-casia.py", when running the following errors arise
> 
> https://user-images.githubusercontent.com/38151088/70859911-47e37380-1ef9-11ea-80a6-ab89372ecb27.png
> 
> Additionally I have problems with "verify.py", since they all give me result = -1
> 
> I hope you can help me, I find myself in an emergency

Regards the NoneType error, this is because the image is not being

> got the same error. There are issues with the segmentation that I could not solve. I get the same error with all the images in the casia1 folder.
> 
> `python3 enroll-single.py --file ../CASIA1/30/030_1_1.jpg
> 
> > > > Enroll for the file  ../CASIA1/001_1_1.jpg
> > > > Traceback (most recent call last):
> > > > File "enroll-single.py", line 33, in 
> > > > template, mask, file = extractFeature(args.file)
> > > > File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/extractFeature.py", line 47, in extractFeature
> > > > ciriris, cirpupil, imwithnoise = segment(im, eyelashes_thres, use_multiprocess)
> > > > File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/segment.py", line 30, in segment
> > > > rowp, colp, rp = searchInnerBound(eyeim)
> > > > File "/home/ianni/PROGRAMMING/Iris-Recognition/python/fnc/boundary.py", line 26, in searchInnerBound
> > > > Y = img.shape[0]
> > > > AttributeError: 'NoneType' object has no attribute 'shape'
> > > > `

Hey I managed to get past this error, you need to comment out line 29 of enroll-single, it reads:
`args.file = "../CASIA1/001_1_1.jpg`

This seems to be a debug line or something that was left behind as it overwrites (i think?) any file input you pass through.
After doing that, it works for me and generates the template files (note you may also need to manually create the folder "templates" and inside that, "temp" like as follows:
`/yourDir/python/templates/temp`

However i cannot quite speak to this fix yet as I always receive a -1 ("No Registered Sample") from the verify.py script... ;(

**Comment by bixiwen** [comment]
Hi, I got the right result.  After `python3 enroll-casia1.py --data_dir CASIA-database`, create the folder " templates\CASIA1" . Use `python3 verify.py --file 002_1_3.jpg --temp_dir templates/CASIA1/`, the result is :
2 samples matched (descending reliability):
         002_1_1.jpg.mat
         002_1_2.jpg.mat

**Comment by ruizs80** [comment]
Hi, I cant get to do a matching. I´ve enrolled 15 templates, but I dont know what happen.
![enrroll-casia1](https://user-images.githubusercontent.com/68344489/105484888-d2fd7400-5c8a-11eb-8628-83e9728cfccf.jpg)
![verify py](https://user-images.githubusercontent.com/68344489/105484902-d98beb80-5c8a-11eb-8362-f2e89fb1a2e0.jpg)

**Comment by ruizs80** [comment]
Here another screen. No matching
![no matching](https://user-images.githubusercontent.com/68344489/105485066-135cf200-5c8b-11eb-9dc2-e55c16988c3c.jpg)

**Comment by Pepper-ALICE** [comment]
oh!  i find a way to deal with that bug, i change all the route of the dataset.
i see that code, 
the link as follows: 
  https://blog.csdn.net/qq_44710529/article/details/126175343?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165967342416781667841897%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=165967342416781667841897&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~times_rank-1-126175343-null-null.142^v39^pc_rank_34,185^v2^control&utm_term=Python删除批量删除外层文件夹&spm=1018.2226.3001.4187
